pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [fthomas]
      label:
        add: [dependency-update]
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=continuous-integration/travis-ci/pr      
      - body~=labels:.*semver-patch
    actions:
      merge:
        method: merge
